# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hero_id',
            field=models.IntegerField(default=0),
        ),
    ]
